CREATE TABLE IF NOT EXISTS ProgSocTest;
USE ProgSocTest;
CREATE TABLE IF NOT EXISTS ProgSocTest (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    Name VARCHAR(255) NOT NULL,
    Price VARCHAR(255) NOT NULL,
    Availability VARCHAR(255) NOT NULL, 
    LastChecked VARCHAR(255) NOT NULL
    );
